### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [Guillaume351/NoFlyHack#10]
You do realize it only works when your Y coordinate is below 24 :-1:

**Comment by Guillaume351** [comment]
Hum why ? Anyway I don't use this plugin :|

**Comment by ghost** [comment]
didnt you know what getY does?!

**Comment by ghost** [comment]
they will get kicked if theyre Y coordinate reaches less than 24

**Comment by Guillaume351** [comment]
On the newer version, no. Can you copy / paste the problem ?

**Comment by ghost** [comment]
nvm then
